development: 
  adapter: postgresql 
  encoding: utf8
  database: ptucker_development 
  host: 127.0.0.1  

test: 
  adapter: postgresql 
  encoding: utf8
  database: ptucker_test
  host: 127.0.0.1  
