development: 
  adapter: postgresql 
  encoding: utf8
  database: dejaset_development
  host: 127.0.0.1  

test: 
  adapter: postgresql 
  encoding: utf8
  database: dejaset_development
  host: 127.0.0.1  
